// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Olha26_IGZFzIPkwTeXcWad9TO13KKc',
    appId: '1:987353329091:web:04cc8de454754326de6176',
    messagingSenderId: '987353329091',
    projectId: 'video-chat-d96c5',
    authDomain: 'video-chat-d96c5.firebaseapp.com',
    storageBucket: 'video-chat-d96c5.appspot.com',
    measurementId: 'G-SFNHB5Z69B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuuCiDbBVBC4rMZnfF5zEXvNAka8un5E',
    appId: '1:987353329091:android:3bc4e906a296e176de6176',
    messagingSenderId: '987353329091',
    projectId: 'video-chat-d96c5',
    storageBucket: 'video-chat-d96c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkpKLsKgEJDNZO-_hlDMYf2YyZV_EG3I0',
    appId: '1:987353329091:ios:b629a5de780a16c2de6176',
    messagingSenderId: '987353329091',
    projectId: 'video-chat-d96c5',
    storageBucket: 'video-chat-d96c5.appspot.com',
    iosBundleId: 'com.example.videoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkpKLsKgEJDNZO-_hlDMYf2YyZV_EG3I0',
    appId: '1:987353329091:ios:b629a5de780a16c2de6176',
    messagingSenderId: '987353329091',
    projectId: 'video-chat-d96c5',
    storageBucket: 'video-chat-d96c5.appspot.com',
    iosBundleId: 'com.example.videoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Olha26_IGZFzIPkwTeXcWad9TO13KKc',
    appId: '1:987353329091:web:1c11eadfdf68b98bde6176',
    messagingSenderId: '987353329091',
    projectId: 'video-chat-d96c5',
    authDomain: 'video-chat-d96c5.firebaseapp.com',
    storageBucket: 'video-chat-d96c5.appspot.com',
    measurementId: 'G-6DCQ6LS2E1',
  );
}
